basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [path('', views.basket_detail, name='basket_detail'),
               path('add/<int:id>', views.basket_add, name='basket_add'),
               path('remove<int:id>', views.basket_remove, name='basket_remove')]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = ([path('', views.product_list, name='product_list'),
                path('<int:id>', views.product_detail, name='product_detail')])

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls')),
    path('', include('product.urls'))
]

basket/models.py
from _decimal import Decimal
from product.models import Product
from shop import settings


class Basket(object):
    def __init__(self, request):
        """
        Init Basket
        :param request: Request Object
        """
        self.session = request.session
        basket = self.session.get(settings.BASKET_SESSION_ID)
        if not basket:
            basket = self.session[settings.BASKET_SESSION_ID] = {}
        self.basket = basket

    def __iter__(self):
        """
        Iterator
        :return:
        """
        products_id = self.basket.keys()
        products = Product.objects.filter(id__in=products_id)
        for product in products:
            self.basket[str(product.id)]['product'] = product

        for item in self.basket.values():
            item['price'] = Decimal(item['price'])
            yield item

    def add(self, product):
        """
        Add Product to Basket
        :param product: Product object
        :return:
        """
        if str(product.id) not in self.basket:
            self.basket[product.id] = {'price': str(product.price)}
        self.save()

    def save(self):
        """
        Save Basket in session
        :return:
        """
        self.session[settings.BASKET_SESSION_ID] = self.basket
        self.session.modified = True

    def remove(self, product):
        """
        Remove Product from Basket
        :param product: Product object
        :return:
        """
        if str(product.id) in self.basket:
            del self.basket[str(product.id)]
            self.save()

    def __len__(self):
        """
        Get Product Count
        :return:
        """
        return len(self.basket.values())

    def clear(self):
        """
        Clear Basket
        :return:
        """
        del self.session[settings.BASKET_SESSION_ID]
        self.session.modified = True

    def get_total_price(self):
        """
        Get total Price
        :return:
        """
        return sum(Decimal(item['price']) for item in self.basket.values())

order/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from product.models import Product
from shop import settings


class Order(models.Model):
    """
    Order Model
    """
    phone = PhoneNumberField(null=False, blank=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=100)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_price() for item in self.items.all())

    def save_user_info(self, request):
        request.session[settings.USER_INFO_SESSION_ID] = {'phone': str(self.phone), 'first_name': self.first_name,
                                                          'last_name': self.last_name, 'address': self.address,
                                                          'city': self.city}


class OrderItem(models.Model):
    """
    Order Item Model
    """
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return '{}'.format(self.id)

    def get_price(self):
        return self.price

product/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Product(models.Model):
    """
    Model for Product
    """
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.id,])

order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    """
    Order Creation Form Class
    """
    class Meta:
        model = Order
        fields = ['phone', 'first_name', 'last_name', 'address', 'city']

basket/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views.decorators.http import require_POST

from basket.models import Basket
from product.models import Product
from order.forms import OrderCreateForm
from order.models import OrderItem
from shop import settings


@require_POST
def basket_add(request, id):
    """
    Add Product to Basket
    :param request:
    :param id:
    :return:
    """
    basket = Basket(request)
    product = get_object_or_404(Product, id=id)
    if request.POST:
        basket.add(product)

    return redirect('basket:basket_detail')


def basket_remove(request, id):
    """
    Remove Product from Basket
    :param request:
    :param id:
    :return:
    """
    basket = Basket(request)
    product = get_object_or_404(Product, id=id)
    basket.remove(product)
    return redirect('basket:basket_detail')


def basket_detail(request):
    """
    Basket Detail Page
    :param request:
    :return:
    """
    basket = Basket(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save()
            order.save_user_info(request)

            for item in basket:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'])
            basket.clear()

            return render(request, 'basket/order_completed.html',
                          {'order': order})
    else:
        user_info = request.session.get('user_info')
        if user_info:
            form = OrderCreateForm(initial={'phone': user_info['phone'], 'first_name': user_info['first_name'],
                                            'last_name': user_info['last_name'], 'address': user_info['address'],
                                            'city': user_info['city']})
        else:
            form = OrderCreateForm()

    return render(request, 'basket/detail.html', {'basket': basket, 'form': form})

product/views.py
from django.shortcuts import render, get_object_or_404

from product.models import Product


# Create your views here.
def product_list(request):
    """
    Product List View
    :param request:
    :return:
    """
    products = Product.objects.all()
    return render(request, 'product/products_list.html', {'products': products})


def product_detail(request, id):
    """
    Product Detail View
    :param request:
    :param id:
    :return:
    """
    product = get_object_or_404(Product, id=id)
    return render(request, 'product/product.html', {'product': product})

shop/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    </head>
<body>
<div class="cart">
    {% if basket|length > 0 %}
        Your cart:
        <a href="{% url "basket:basket_detail" %}">
            {{ basket|length }} items,
            ${{ basket.get_total_price }}
        </a>
    {% else %}
        Your cart is empty.
    {% endif %}

</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>

shop/templates/basket/detail.html
{% extends "base.html" %}
{% load static %}
 
{% block title %}
    Your shopping cart
{% endblock %}
 
{% block content %}
    {% for item in basket %}
        {% with product=item.product %}
            {{ product.name }}
            <a href="{% url "basket:basket_remove" product.id %}">Remove</a>
            <{{ product.price }}</td>
        {% endwith %}
    {% endfor %}
    <p class="text-right">
        <a href="{% url "product:product_list" %}" class="button light">Continue
            shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>

    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Place order"></p>
        {% csrf_token %}
    </form>
{% endblock %}  

shop/templates/basket/order_completed.html
{% extends "base.html" %}

{% block title %}
    Thank you
{% endblock %}

{% block content %}
<a href="{% url "product:product_list" %}" class="button light">Continue
            shopping</a>
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/templates/product/product.html
{% extends "base.html" %}

{% block content %}
    <div class="product-detail">
    <h1>{{ product.name }}</h1>
    <p class="price">${{ product.price }}</p>
    </div>
    <form action="{% url "basket:basket_add" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
{% endblock %}

shop/templates/product/products_list.html
{% extends "base.html" %}

{% block content %}
    {% for product in products %}
        <div class="item">
          <a href="{{ product.get_absolute_url }}">
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          ${{ product.price }}
        </div>
        {% endfor %}
    </div>
{% endblock %}